### ISSUE TITLE
Namespace handling todo list

### ISSUE THREAD

**Issue by evilpie** [WICG/sanitizer-api#171]
This might be incomplete, but I will try to collect what I find here. (To be updated)

- [ ] #167 Don't treat SVG / MathML elements as always unknown (This might involve some kind of baseline list here as well)
- [x] #146 The current way of specifying `namespace:element ` is not acceptable
- [x] I am not totally convinced that we should be using "[the rules for parsing tokens in foreign content](https://html.spec.whatwg.org/multipage/parsing.html#parsing-main-inforeign)" in [normalize element name](https://wicg.github.io/sanitizer-api/#normalize-element-name) at all.
- [ ]  xlink:href isn't handled at all e.g., #168
- [ ] Aggressively disallow/drop elements and attributes with unknown (non-html/svg/math) namespaces?

**Comment by mozfreddyb** [comment]
Let's track the issues individually and close this one out
